import * as fs from 'node:fs';
import * as path from 'node:path';
import {
    isLexicallyContained,
    resolveRootRealPath,
    escapesRootViaRealpath,
    isDirectoryShaped,
} from '../utils/path-guard.js';

/**
 * Base names of the three generated per-workspace index files, in the order
 * they are written by {@link writeWorkspaceIndexFiles} and probed by
 * {@link checkIndexFileStatus}.
 *
 * - `README.md` — human-facing index, browsed directly in the workspace folder.
 * - `AGENTS.md` — the same index plus an agent-directives block, loaded into an
 *   agent's context when it starts working in the folder.
 * - `CLAUDE.md` — a one-line `@AGENTS.md` pointer, mirroring the pattern this
 *   repository already uses at its own root, so agents without native
 *   `AGENTS.md` support still find the directives.
 */
export const WORKSPACE_INDEX_FILE_NAMES: readonly string[] = ['README.md', 'AGENTS.md', 'CLAUDE.md'];

/**
 * Marks the start of the block of each index file that is owned and
 * regenerated by this module. Text before this marker is preserved verbatim
 * across regenerations.
 */
export const GENERATED_BEGIN_MARKER = '<!-- paralizer:generated:begin -->';

/**
 * Marks the end of the generated block. Text after this marker is preserved
 * verbatim across regenerations.
 */
export const GENERATED_END_MARKER = '<!-- paralizer:generated:end -->';

/**
 * A single repository row rendered into the workspace index tables.
 */
export interface WorkspaceIndexRepositoryRow {
    /** Repository ID — also the folder name under the workspace folder. */
    id: string;

    /** Repository display name. */
    name: string;

    /** Repository description. Empty string when none is set. */
    description: string;

    /** Remote Git URL. */
    url: string;
}

/**
 * Everything the renderers need to produce the three index files for one
 * workspace. Callers (the artefact choke-point in `workspace-artifacts.ts`)
 * are responsible for resolving this context from the data layer; this
 * module never reads `ProjectManager`/`RepositoryManager` itself.
 */
export interface WorkspaceIndexContext {
    /** Root folder containing all project subdirectories. */
    projectsFolder: string;

    /** Project ID (also the per-project subdirectory name). */
    projectId: string;

    /** Project display name. */
    projectName: string;

    /** Project description. Empty string when none is set. */
    projectDescription: string;

    /** Workspace ID. */
    workspaceId: string;

    /** Workspace description. Empty string when none is set. */
    workspaceDescription: string;

    /** Workspace free-text notes. Empty string when none are set. */
    workspaceNotes: string;

    /** Repository rows, in the order they should appear in the table (`project.Repositories` order). */
    repositories: WorkspaceIndexRepositoryRow[];

    /** Absolute URL to this workspace's GUI page (built from `config.serverPort`). */
    guiUrl: string;

    /** The tool's own version, from `getToolVersion()`. */
    toolVersion: string;

    /** ISO 8601 timestamp recorded as the generation time. */
    generatedAt: string;
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

/**
 * Neutralises a string for safe embedding as a single Markdown table cell.
 *
 * Escapes `|` (which would otherwise be interpreted as a column separator),
 * collapses CR/LF sequences to a single space (a raw newline inside a cell
 * breaks the row), and trims leading/trailing whitespace.
 *
 * Used for every user-supplied string embedded in the generated index body —
 * not only literal table cells — because a value containing an unescaped `|`
 * or newline placed anywhere near the table can also corrupt Markdown table
 * parsing in surrounding lines (AC-06).
 */
export function escapeMarkdownCell(value: string): string {
    return value
        .replace(/\|/g, '\\|')
        .replace(/\r\n|\r|\n/g, ' ')
        .trim();
}

/**
 * Renders the shared metadata + repository-table body used by both
 * `README.md` and `AGENTS.md`. Deterministic apart from `ctx.generatedAt`.
 */
function renderIndexBody(ctx: WorkspaceIndexContext): string {
    const lines: string[] = [];

    lines.push(`# ${escapeMarkdownCell(ctx.projectName)} — Workspace ${ctx.workspaceId}`);
    lines.push('');

    const projectDescription = escapeMarkdownCell(ctx.projectDescription);
    if (projectDescription !== '') {
        lines.push(projectDescription);
        lines.push('');
    }

    lines.push(`**Workspace:** ${ctx.workspaceId}`);

    const workspaceDescription = escapeMarkdownCell(ctx.workspaceDescription);
    if (workspaceDescription !== '') {
        lines.push('');
        lines.push(workspaceDescription);
    }

    const workspaceNotes = escapeMarkdownCell(ctx.workspaceNotes);
    if (workspaceNotes !== '') {
        lines.push('');
        lines.push(`**Notes:** ${workspaceNotes}`);
    }

    lines.push('');
    lines.push('## Repositories');
    lines.push('');
    lines.push('| Folder | Name | Description | Remote URL |');
    lines.push('|---|---|---|---|');

    for (const repo of ctx.repositories) {
        const name = escapeMarkdownCell(repo.name);
        const description = escapeMarkdownCell(repo.description);
        const url = escapeMarkdownCell(repo.url);
        lines.push(`| ${repo.id} | ${name} | ${description} | ${url} |`);
    }

    lines.push('');
    lines.push(`**GUI:** ${ctx.guiUrl}`);
    lines.push('');
    lines.push(`_Generated by paralizer ${ctx.toolVersion} at ${ctx.generatedAt}._`);

    return lines.join('\n');
}

/**
 * Directives block appended to `AGENTS.md` only. Deliberately excludes live
 * git state (branch, dirty status, ahead/behind) — the GUI owns that, and a
 * generated file reporting it would be wrong within minutes.
 */
const AGENT_DIRECTIVES_BLOCK = [
    '## Agent Directives',
    '',
    '- Each subfolder listed above is an independent git repository with its own instruction files (e.g. `AGENTS.md`, `CLAUDE.md`) that must be read before working in it.',
    '- Do not use relative imports across repository/folder boundaries.',
    '- Live branch, working-tree status, and ahead/behind counts are not tracked in this file — use the Paralizer GUI link above for current git state.',
    '- Content between the generated markers above is regenerated automatically; edits outside the markers are preserved.',
].join('\n');

/**
 * Renders the generated body of `README.md`: project/workspace metadata, the
 * repository table, and the GUI link. Omits the agent-directives block.
 */
export function renderWorkspaceReadme(ctx: WorkspaceIndexContext): string {
    return renderIndexBody(ctx);
}

/**
 * Renders the generated body of `AGENTS.md`: the same content as
 * {@link renderWorkspaceReadme} plus the agent-directives block.
 */
export function renderWorkspaceAgents(ctx: WorkspaceIndexContext): string {
    return `${renderIndexBody(ctx)}\n\n${AGENT_DIRECTIVES_BLOCK}`;
}

/**
 * Renders the generated body of `CLAUDE.md`: a single `@AGENTS.md` pointer
 * line, mirroring this repository's own root `CLAUDE.md`. Keeps the design
 * independent of any particular agent's native `AGENTS.md` support.
 */
export function renderClaudePointer(): string {
    return '@AGENTS.md';
}

// ---------------------------------------------------------------------------
// Marker detection (single implementation — shared by merge, remove, and
// the status probe, per AC-08 / AC-19)
// ---------------------------------------------------------------------------

/**
 * The single implementation of "does this file's content contain the
 * generated-block begin marker" — the predicate every other marker-aware
 * function in this module is built on.
 */
function hasBeginMarker(content: string): boolean {
    return content.includes(GENERATED_BEGIN_MARKER);
}

// ---------------------------------------------------------------------------
// Merge
// ---------------------------------------------------------------------------

/**
 * Merges a freshly rendered generated body into an existing file's content,
 * preserving everything outside the generated fence.
 *
 * - When `existing` is `null` (file does not yet exist), returns a new file
 *   consisting of exactly the fenced block.
 * - When `existing` contains no begin marker, it is treated as hand-authored:
 *   the content is returned unchanged and `skipped` is `true`.
 * - Otherwise, the region between the begin and end markers is replaced with
 *   `generatedBody`; text before the begin marker and after the end marker
 *   (if present) is preserved verbatim. When no end marker follows the begin
 *   marker, the fenced replacement extends to the end of the file.
 *
 * @param existing      - Current file content, or `null` if the file does not exist.
 * @param generatedBody - The freshly rendered content to place inside the fence.
 */
export function mergeGeneratedContent(
    existing: string | null,
    generatedBody: string,
): { content: string; skipped: boolean } {
    const fenced = `${GENERATED_BEGIN_MARKER}\n${generatedBody}\n${GENERATED_END_MARKER}`;

    if (existing === null) {
        return { content: `${fenced}\n`, skipped: false };
    }

    if (!hasBeginMarker(existing)) {
        return { content: existing, skipped: true };
    }

    const beginIdx = existing.indexOf(GENERATED_BEGIN_MARKER);
    const endIdx = existing.indexOf(GENERATED_END_MARKER, beginIdx);

    const before = existing.slice(0, beginIdx);
    const after = endIdx === -1 ? '' : existing.slice(endIdx + GENERATED_END_MARKER.length);

    return { content: `${before}${fenced}${after}`, skipped: false };
}

// ---------------------------------------------------------------------------
// Writer
// ---------------------------------------------------------------------------

/**
 * Resolves the workspace folder for `ctx.projectId` / `ctx.workspaceId` and
 * writes (or merges into) the three generated index files.
 *
 * - **No-op, no `mkdir`, when the workspace folder does not exist.** The
 *   folder's existence is a load-bearing signal elsewhere in the system (an
 *   uninitialised workspace is reported healthy, and the regenerate-file
 *   endpoint rejects it); writing an index file into a folder that does not
 *   exist would fabricate an initialised-looking workspace.
 * - For each of the three target files, runs — in order — the lexical
 *   containment check, the realpath symlink-escape check, and the
 *   directory-shape check, before any read or write. A target that fails any
 *   guard is reported in `skipped` rather than written, and never throws.
 * - A target that exists without the generated begin marker is treated as
 *   hand-authored: left untouched and reported in `skipped` (AC-08).
 *
 * @returns The base names written, and the base names skipped (guard
 *          rejection or hand-authored file), each drawn from
 *          {@link WORKSPACE_INDEX_FILE_NAMES}.
 */
export function writeWorkspaceIndexFiles(ctx: WorkspaceIndexContext): { written: string[]; skipped: string[] } {
    const workspaceFolder = path.join(ctx.projectsFolder, ctx.projectId, ctx.workspaceId);

    if (!fs.existsSync(workspaceFolder)) {
        return { written: [], skipped: [] };
    }

    // Two distinct roots are used by the two guards below, deliberately kept
    // separate rather than unified into one:
    // - `resolvedProjectsFolder` (lexical `path.resolve`, no symlink
    //   resolution) is compared against a target path built the same
    //   (lexical) way, so it catches a `..`-escaping `projectId`/`workspaceId`.
    // - `realProjectsFolder` (realpath) is compared against a realpath'd
    //   target ancestor, so it catches a symlink escape.
    // Comparing a realpath'd target against a lexical-only root (or vice
    // versa) would misfire on any system where the configured root itself
    // sits behind a symlink (e.g. macOS's `/tmp` -> `/private/tmp`), rejecting
    // every legitimate write.
    const resolvedProjectsFolder = path.resolve(ctx.projectsFolder);
    const realProjectsFolder = resolveRootRealPath(ctx.projectsFolder);

    const bodiesByName: Record<string, string> = {
        'README.md': renderWorkspaceReadme(ctx),
        'AGENTS.md': renderWorkspaceAgents(ctx),
        'CLAUDE.md': renderClaudePointer(),
    };

    const written: string[] = [];
    const skipped: string[] = [];

    for (const name of WORKSPACE_INDEX_FILE_NAMES) {
        const targetPath = path.join(workspaceFolder, name);
        const resolvedTarget = path.resolve(targetPath);

        if (!isLexicallyContained(resolvedTarget, resolvedProjectsFolder)) {
            skipped.push(name);
            continue;
        }

        if (escapesRootViaRealpath(resolvedTarget, realProjectsFolder)) {
            skipped.push(name);
            continue;
        }

        if (isDirectoryShaped(resolvedTarget)) {
            skipped.push(name);
            continue;
        }

        let existing: string | null = null;
        if (fs.existsSync(targetPath)) {
            try {
                existing = fs.readFileSync(targetPath, 'utf8');
            } catch {
                // Unreadable existing file — treat conservatively as
                // hand-authored/unmanaged rather than risking clobbering it.
                skipped.push(name);
                continue;
            }
        }

        const { content, skipped: mergeSkipped } = mergeGeneratedContent(existing, bodiesByName[name]);
        if (mergeSkipped) {
            skipped.push(name);
            continue;
        }

        fs.writeFileSync(targetPath, content, 'utf8');
        written.push(name);
    }

    return { written, skipped };
}

// ---------------------------------------------------------------------------
// Remover
// ---------------------------------------------------------------------------

/**
 * Removes the generated index files for a workspace.
 *
 * Only removes a file that contains the generated begin marker; a
 * hand-authored file (no marker) is left in place, mirroring the writer's
 * skip guarantee (AC-08). Tolerates a missing workspace folder or a missing
 * individual file (`ENOENT`) as a silent no-op for that file.
 */
export function removeWorkspaceIndexFiles(projectsFolder: string, projectId: string, workspaceId: string): void {
    const workspaceFolder = path.join(projectsFolder, projectId, workspaceId);

    for (const name of WORKSPACE_INDEX_FILE_NAMES) {
        const targetPath = path.join(workspaceFolder, name);

        let content: string;
        try {
            content = fs.readFileSync(targetPath, 'utf8');
        } catch (err) {
            if ((err as NodeJS.ErrnoException).code === 'ENOENT') continue;
            throw err;
        }

        if (!hasBeginMarker(content)) continue;

        try {
            fs.rmSync(targetPath);
        } catch (err) {
            if ((err as NodeJS.ErrnoException).code === 'ENOENT') continue;
            throw err;
        }
    }
}

// ---------------------------------------------------------------------------
// Status probe
// ---------------------------------------------------------------------------

/**
 * Read-only status probe for the three generated index files, consumed by
 * `checkWorkspaceHealth()`. Shares {@link hasBeginMarker} — the module's one
 * marker-detection primitive — with {@link mergeGeneratedContent} and
 * {@link removeWorkspaceIndexFiles}, so a file reported here as `unmanaged`
 * is guaranteed to be the same file the writer would report as skipped
 * (AC-08, AC-19).
 *
 * Classifies each file in {@link WORKSPACE_INDEX_FILE_NAMES} as:
 * - **missing** — absent from disk;
 * - **present-managed** — exists and contains the begin marker (listed in
 *   neither returned array);
 * - **present-unmanaged** — exists without the begin marker (hand-authored).
 *
 * Returns both arrays empty when the workspace folder does not exist, so
 * callers need no separate folder-existence branch. Performs no writes and
 * no `mkdir`.
 */
export function checkIndexFileStatus(
    projectsFolder: string,
    projectId: string,
    workspaceId: string,
): { missing: string[]; unmanaged: string[] } {
    const workspaceFolder = path.join(projectsFolder, projectId, workspaceId);

    const missing: string[] = [];
    const unmanaged: string[] = [];

    if (!fs.existsSync(workspaceFolder)) {
        return { missing, unmanaged };
    }

    for (const name of WORKSPACE_INDEX_FILE_NAMES) {
        const targetPath = path.join(workspaceFolder, name);

        if (!fs.existsSync(targetPath)) {
            missing.push(name);
            continue;
        }

        let content: string;
        try {
            content = fs.readFileSync(targetPath, 'utf8');
        } catch {
            // Unreadable — treat conservatively as unmanaged rather than
            // throwing out of a documented side-effect-free status probe.
            unmanaged.push(name);
            continue;
        }

        if (!hasBeginMarker(content)) {
            unmanaged.push(name);
        }
    }

    return { missing, unmanaged };
}
